baseURL: http://dataskool.netlify.com/
languageCode: en-us
title: পরিসংখ‍্যান পাঠশালা - School of Statistics
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: পরিসংখ‍্যান পাঠশালা
    # Hero subtitle (optional)
    subtitle: পরিসংখ‍্যান ও ডেটা সায়েন্সের বাংলা রিসোর্স
    # Button text
    buttontext: সাবস্ক্রাইব ফ্রি
    # Where the main hero button links to
    buttonlink: "http://eepurl.com/dD8iV1"
    # Hero image (from /images/___)
    image: illustrations/worker1.svg
    # Footer logos (from /images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: বই
    sublinks:
    - title: পরিসংখ‍্যান পরিচিতি
      url: #
    - title: R পরিচিতি
      url: #
    # - title: Dropdown item
    #   url: /
  # - title: Log in
  #   url: /
  - title: ব্লগ
    url: https://blog.dataskool.org
  # - title: টিউটোরিয়াল
  #   url: /
  - title: সাবস্ক্রাইব
    url: http://eepurl.com/dD8iV1
    button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    # - title: User
    #   icon: user
    #   links:
    #   - text: Profile
    #     url: /
    #   - text: Account
    #     url: /
    #   - text: Settings
    #     url: /
    # - title: Messages
    #   icon: envelope
    #   links:
    #   - text: Inbox
    #     url: /
    #   - text: Compose
    #     url: /
    # - title: Images
    #   icon: image
    #   links:
    #   - text: Library
    #     url: /
    #   - text: Upload
    #     url: /
    # - title: Settings
    #   icon: cog
    #   links:
    #   - text: User settings
    #     url: /
    #   - text: App settings
    #     url: /
  section1:
    title: অতি যত্নে তৈরী করা হচ্ছে ...
    subtitle: আপডেট পেতে সাবস্ক্রাইব করুন 
    tiles:
    - title: পরিসংখ‍্যান পরিচিতি
      icon: mouse-globe
      text: পরিসংখ‍্যানের প্রাথমিক ধারণা
      url: http://eepurl.com/dD8iV1
      buttonText: বের হলে জানাও
    - title: R পরিচিতি
      icon: laptop-cloud
      text: বাংলায় R সফটওয়‍্যার পরিচিতি
      url: http://eepurl.com/dD8iV1
      buttonText: বের হলে জানাও
    - title: ফলিত পরিসংখ‍্যান ও ডেটা সায়েন্স
      icon: laptop-globe
      text: ব‍্যবহারিক পরিসংখ‍্যান ও ডেটা এনালিসিস
      url: http://eepurl.com/dD8iV1
      buttonText: বের হলে জানাও
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  footer:
    # Logo (from /images/logos/___)
    logo: ds-logo2.svg
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    product:
    - text: আমাদের রিসোর্স
      link: /
    - text: রোডম‍্যাপ
      link: /
    - text: ফিচার রিকোয়েস্ট
      link: /
    blogroll:
    - text: লেটেস্ট ব্লগ
      link: /
    - text: টিউটোরিয়াল আর্টিকেল
      link: /
    - text: ক‍্যারিয়ার
      link: /
    docs:
    - text: সর্বাধিক জিজ্ঞাস‍্য
      link: /
    - text: বই লিখতে আগ্রহী
      link: /
    - text: যোগাযোগ
      link: / 

    
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
